name: CI
on: [push]
jobs:
  publish-packages:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node_version: "14"
          registry-url: "https://registry.npmjs.org"
      - run: yarn install
      - run: yarn bootstrap
      - run: yarn release:build
      - run: yarn release:publish
