name: CI
on: [push]
jobs:
  install-lerna:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node_version: "14"
          registry-url: "https://registry.npmjs.org"
      - run: yarn install
      - run: yarn bootstrap
      - run: yarn release:build
